controllers:
    resource: ../src/Controller/
    type: attribute

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register


app_login:
    path: /connexion
    controller: App\Controller\AuthController::login
    methods: [GET, POST]


app_logout:
    path: /logout

app_figure_detail:
    path: '/figure/{id}'
    controller: App\Controller\FiguresController::show
    requirements:
        id: \d+

app_user_edit:
    path: /edit-profile
    controller: App\Controller\UsersController::editProfile
    methods: [ GET, POST ]

app_forgot_password:
    path: /forgot-password
    controller: App\Controller\SecurityController::forgotPassword
    methods: [GET, POST]

app_reset_password_demande:
    path: /reset-password-demande
    controller: App\Controller\ResetPasswordController::index  
    methods: [GET, POST]

